# ci.yml
name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            triplet: x64-linux
          - os: ubuntu-latest
            triplet: x86-linux
          - os: windows-latest
            triplet: x64-windows
          - os: windows-latest
            triplet: x86-windows
          - os: macos-latest
            triplet: x64-osx
    env:
      VCPKG_DEFAULT_TRIPLET: ${{ matrix.triplet }}
      VCPKG_DEFAULT_HOST_TRIPLET: ${{ matrix.triplet }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup CMake
        uses: lukka/get-cmake@latest

      - name: Install dependencies (Non-Windows)
        if: runner.os != 'Windows'
        run: |
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            sudo apt-get update
            sudo apt-get install -y build-essential cmake libsdl3-dev
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            brew update
            brew install cmake sdl3
          fi

      - name: Setup vcpkg (Windows only)
        if: runner.os == 'Windows'
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgJsonGlob: 'vcpkg.json'

      - name: Configure and build (Debug)
        run: |
          cmake -S . -B build/debug -DCMAKE_BUILD_TYPE=Debug \
            ${{ runner.os == 'Windows' && format('-DCMAKE_TOOLCHAIN_FILE={0}/vcpkg/scripts/buildsystems/vcpkg.cmake', github.workspace) || '' }}
          cmake --build build/debug --config Debug

      - name: Configure and build (Release)
        run: |
          cmake -S . -B build/release -DCMAKE_BUILD_TYPE=Release \
            ${{ runner.os == 'Windows' && format('-DCMAKE_TOOLCHAIN_FILE={0}/vcpkg/scripts/buildsystems/vcpkg.cmake', github.workspace) || '' }}
          cmake --build build/release --config Release
